# Generated by Django 4.2.6 on 2023-12-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_caller_game_caller_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="caller",
            name="current_call_sid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
