# Generated by Django 4.2.6 on 2023-12-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_caller_current_call_sid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caller",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
