# Generated by Django 4.2.6 on 2023-12-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_caller_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwilioCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("post_blob", models.JSONField()),
            ],
        ),
    ]
