# Generated by Django 4.2.6 on 2023-12-07 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_twiliocalllog"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TwilioCallLog",
            new_name="TwilioLog",
        ),
    ]
