# Generated by Django 4.2.6 on 2023-12-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_twiliocalllog_twiliolog"),
    ]

    operations = [
        migrations.AddField(
            model_name="caller",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="caller",
            name="state",
            field=models.CharField(
                choices=[
                    ("hungup", "hungup"),
                    ("waiting", "waiting"),
                    ("ingame", "ingame"),
                ],
                max_length=255,
            ),
        ),
    ]
