# Generated by Django 4.2.6 on 2023-12-07 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_caller_updated_alter_caller_state"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="caller",
            name="phone_number",
        ),
    ]
