# Generated by Django 4.2.6 on 2023-12-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_caller_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="last_player_1_move",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="last_player_2_move",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
