# Generated by Django 4.2.6 on 2023-12-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_caller_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="round",
            name="player1_recording_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="round",
            name="player2_recording_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
