# Generated by Django 4.2.6 on 2023-12-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_rename_last_player_1_move_round_player_1_move_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Caller",
            new_name="CallSession",
        ),
    ]
