# Generated by Django 4.2.6 on 2023-12-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_rename_caller_callsession"),
    ]

    operations = [
        migrations.RenameField(
            model_name="callsession",
            old_name="current_call_sid",
            new_name="call_sid",
        ),
    ]
