# Generated by Django 4.2.6 on 2023-12-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_rename_current_call_sid_callsession_call_sid"),
    ]

    operations = [
        migrations.AddField(
            model_name="twiliolog",
            name="view_function",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
