# Generated by Django 4.2.6 on 2023-12-08 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_rename_post_blob_twiliolog_payload"),
    ]

    operations = [
        migrations.RenameField(
            model_name="round",
            old_name="player_1_move",
            new_name="player1_move",
        ),
        migrations.RenameField(
            model_name="round",
            old_name="player_2_move",
            new_name="player2_move",
        ),
    ]
