# Generated by Django 4.2.6 on 2023-12-08 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_rename_player_1_move_round_player1_move_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="round",
            name="player1",
        ),
        migrations.RemoveField(
            model_name="round",
            name="player2",
        ),
        migrations.AddField(
            model_name="round",
            name="player1_session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="player1_session",
                to="core.callsession",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="round",
            name="player2_session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="player2_session",
                to="core.callsession",
            ),
            preserve_default=False,
        ),
    ]
