# Generated by Django 4.2.6 on 2023-12-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_remove_round_player1_remove_round_player2_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="round",
            old_name="winner",
            new_name="winner_session",
        ),
    ]
