# Generated by Django 4.2.6 on 2023-12-08 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_rename_winner_round_winner_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="callsession",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
