# Generated by Django 4.2.6 on 2023-12-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_round_round_number_alter_callsession_state_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreadSafe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=80, unique=True)),
            ],
        ),
    ]
