# Generated by Django 4.2.6 on 2023-12-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_threadsafe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callsession",
            name="state",
            field=models.CharField(
                choices=[
                    ("hungup", "hungup"),
                    ("being_welcomed", "being_welcomed"),
                    ("waiting_for_other_player", "waiting_for_other_player"),
                    ("started_round", "started_round"),
                    ("rerecording", "rerecording"),
                    ("waiting_for_transcript", "waiting_for_transcript"),
                    ("listening_to_results", "listening_to_results"),
                ],
                max_length=255,
            ),
        ),
    ]
