# Generated by Django 4.2.6 on 2023-12-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_callsession_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="callsession",
            name="number_of_incorrect_transcripts",
            field=models.IntegerField(default=0),
        ),
    ]
